[build]
  functions = "api/"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"
  DB_TYPE = "sqlserver"
  DB_USER = "promocao_user"
  DB_PASSWORD = "T3cN0!@#"
  DB_SERVER = "201.71.178.65"
  DB_PORT = "6565"
  DB_NAME = "Aleatorio"

[context.production.environment]
  NODE_ENV = "production"
  DB_TYPE = "sqlserver"
  DB_USER = "promocao_user"
  DB_PASSWORD = "T3cN0!@#"
  DB_SERVER = "201.71.178.65"
  DB_PORT = "6565"
  DB_NAME = "Aleatorio"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  DB_TYPE = "sqlserver"
  DB_USER = "promocao_user"
  DB_PASSWORD = "T3cN0!@#"
  DB_SERVER = "201.71.178.65"
  DB_PORT = "6565"
  DB_NAME = "Aleatorio"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  DB_TYPE = "sqlserver"
  DB_USER = "promocao_user"
  DB_PASSWORD = "T3cN0!@#"
  DB_SERVER = "201.71.178.65"
  DB_PORT = "6565"
  DB_NAME = "Aleatorio"